#pragma once
#ifndef EXMACRO_H
#define EXMACRO_H
#if __cpp_impl_three_way_comparison
#define EXLIB_FOR_ALL_COMP_OPS_H(MACRO_NAME) MACRO_NAME(<) MACRO_NAME(>) MACRO_NAME(<=) MACRO_NAME(>=) MACRO_NAME(==) MACRO_NAME(!=) MACRO_NAME(<=>)
#else
#define EXLIB_FOR_ALL_COMP_OPS_H(MACRO_NAME) MACRO_NAME(<) MACRO_NAME(>) MACRO_NAME(<=) MACRO_NAME(>=) MACRO_NAME(==) MACRO_NAME(!=)
#endif
#define EXLIB_FOR_ALL_COMP_OPS(MACRO_NAME) EXLIB_FOR_ALL_COMP_OPS_H(MACRO_NAME)

#endif